version: '3.8'

services:
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cinemadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cinema12345
    ports:
      - "5432:5432"

volumes:
  postgres_data: